name: Build and deploy containers

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push application image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: production
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/gates-app:latest
            ghcr.io/${{ github.repository_owner }}/gates-app:${{ github.sha }}

      - name: Build and push SQL Server image
        uses: docker/build-push-action@v5
        with:
          context: docker/sqlserver
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/gates-sqlserver:latest
            ghcr.io/${{ github.repository_owner }}/gates-sqlserver:${{ github.sha }}

      - name: SSH into VPS and deploy
        if: ${{ secrets.VPS_HOST != '' && secrets.VPS_USER != '' && secrets.SSH_PRIVATE_KEY != '' }}
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/docker/gates
            docker compose pull
            docker compose up -d
